### PR TITLE
Load only required database configuration

### PR DESCRIPTION
**Pull request by defkode**
- also removed desc from establish_connection, so it doesn't appear on task list

### CODE REVIEW

**Comment by pawurb** [comment]
@defkode I don't think it will work. You should probably check if `DATABASE_URL` is present and use it to establish connection. Only fallback to parsing YML file if it is missing.

**Comment by defkode** [comment]
My guess that rails config/database.yml should be reused (contrary to ruby-pg-extras where DATABASE_URL is required)

I checked it locally (with erb syntax), and on heroku where config looks like:

```
production:
  url: <%= ENV['DATABASE_URL'] %>
```

and now it works. Also tests are passing.

On my heroku setup (codebase is large), it is ~8s faster. Pretty big deal when using it as a replacement for heroku-pg-extras

Sorry for marking PR as ready too fast!

**Comment by pawurb** [comment]
For some of my Rails apps I just put `DATABASE_URL` in the `ENV` and not `config/database.yml`. This case must also be supported.

**Comment by pawurb** [comment]
@defkode are you planning to finish this one soon? I'm looking forward to this change so let me know if you won't have time to finish and I can take over.

**Comment by defkode** [comment]
I tried to reuse logic behind ActiveRecord::Base.configurations, maybe you will have more luck with getting it loaded without loading whole Rails application

**Pull request merged**
